name: lubricant-storage
services:
  lubricantstorage.api:
    container_name: lubricantstorage.api
    image: ${DOCKER_REGISTRY-}lubricantstorageapi
    build:
      context: .
      dockerfile: LubricantStorage.API/Dockerfile
    ports:
      - 5173:5005
    environment:
      - Database__ConnectionString=mongodb://user:1234@mongodb:27017/LubricantStorage?authSource=admin
    depends_on:
      - mongodb

  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
     - 27018:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=1234
      - MONGO_INITDB_DATABASE=LubricantStorage
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js

volumes:
  mongodb_data_container: 